#!/bin/sh

#
# libslack - http://libslack.org/
#
# Copyright (C) 1999-2004, 2010, 2020 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#

# 20201111 raf <raf@raf.org>

# Convert an old libslack property file into a libslack-0.5.2 property file.
# Previously, leading spaces were kept. Now they're stripped unless quoted.
# This script quotes leading spaces in old properties files so that they'll
# be preserved by newer versions of libslack.

if [ $# = 0 ]
then
	echo usage: $0 '/etc/properties/* ~/.properties/*' >&2
	exit 1
fi

exec perl -p -i -e 's/(?<!\\)= /=\\ /' "$@"
