#!/bin/sh

touch test10.interpreter
chmod 775 test10.interpreter

echo "#!`pwd`/test10.interpreter" > test10.client
chmod 755 test10.client

../daemon -C "`pwd`/daemon.conf" -n test10 "`pwd`/test10.client"
rm test10.interpreter
