#!/bin/sh
#
# libslack - http://libslack.org/
#
# Copyright (C) 1999-2002, 2004, 2010, 2020-2021 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#

# Modify macros.mk and config.h to exercise optional code
#
# 20210220 raf <raf@raf.org>

perl -pi \
	-e 's/^# (GETOPT := getopt)$/$1/;' \
	-e 's/^# (VSSCANF := vsscanf)$/$1/;' \
	-e 's/^# (SNPRINTF := snprintf)$/$1/;' \
	`find . -name macros.mk`

perl -pi \
	-e 's/^#define (HAVE_GETOPT_LONG) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_VSSCANF) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_STRCASECMP) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_STRNCASECMP) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_STRLCPY) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_STRLCAT) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_SNPRINTF) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_VSNPRINTF) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_ASPRINTF) 1$/\/* #undef $1 *\//;' \
	-e 's/^#define (HAVE_VASPRINTF) 1$/\/* #undef $1 *\//;' \
	`find . -name config.h`

# vi:set ts=4 sw=4:
